name: Publish Python Package

on:
  push:
    branches:
      - feature/*
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Upgrade pip and install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          # If you have additional requirements, install them here too:
          python -m pip install -r requirements.txt

      - name: Build distributions
        run: python -m build

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  # pypi-publish:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   permissions:
  #     id-token: write
  #   environment:
  #     name: pypi
  #   steps:
  #     - name: Download release artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: release-dists
  #         path: dist/

  #     - name: Publish to PyPI
  #       uses: pypa/gh-action-pypi-publish@release/v1
  #       with:
  #         packages-dir: dist/
